### ISSUE TITLE
Local uninitialized variables sometimes being initialized with random values

### ISSUE THREAD

**Issue by evilfactory** [evilfactory/moonsharp#17]
Can be potentially fixed by cherry picking this commit https://github.com/moonsharp-devs/moonsharp/pull/280/commits/b819a48a3604a14fb75f5ca5bcd23f854d6ec243

Reproduction code:
```lua
local function test()
   for k, v in pairs{1} do 
       local my
       return my
   end
end
print(test()) -- returns {1} instead of nil
```

**Comment by Saalvage** [comment]
Fixed in #23
